### ISSUE TITLE
Could the author provied donor_ids.tsv

### ISSUE THREAD

**Issue by Landau1994** [jibsch/iBlastoids_scripts#1]
Hello jibsch, thanks for uploading your scripts to GitHub. But I found your script needs a table donor_ids.tsv. I notice the iBlastoids_donor.sh script will deconvolute donor information and I am trying to run cellranger from the fastq file download from GEO to run this script. However,  I am not sure whether running iBlastoids_donor.sh will give the right result.  Could you provide donor_ids_tsv directly? 
Thanks a lot!

**Comment by Landau1994** [comment]
Sorry, I found this data can be obtained from the supplementary table I of the paper, https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-03372-y/MediaObjects/41586_2021_3372_MOESM3_ESM.xlsx

**Comment by jibsch** [comment]
I was about to send you this. Glad you found it already.

**Comment by Landau1994** [comment]
> Sorry, I found this data can be obtained from the supplementary table I of the paper, https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-03372-y/MediaObjects/41586_2021_3372_MOESM3_ESM.xlsx



> I was about to send you this. Glad you found it already.

Thanks!
